### ISSUE TITLE
OPQBot地址跟机器人qq怎么

### ISSUE THREAD

**Issue by Crowsflying** [traceless0929/Traceless.OPQ#4]
http://192.168.xx.xx:2333/#/dashboard opqbot我可以用这个地址登录进控制台，但是配置文件的地址和机器人qq该如何添加呢
我填写这个websokcet还是错误的  如果成功了 有无ui界面可以操作呢
   <add key="address" value="http://192.168.xx.xx:2333" />
    <add key="robotqq" value="341111111" />

**Comment by traceless0929** [comment]
https://github.com/traceless0929/Traceless.OPQ/blob/master/Traceless.Robot/App.config 配置参考该文件，https://github.com/opq-osc/OPQ/wiki/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97 OPQ使用参考OPQ WIKI
按照你给出的问题内容，如果你没有修改过相关配置 App.config中的address填http://192.168.xx.xx:2333/就行了【如果你的SDK运行的机器和OPQ本体在一个内网的话】

**Comment by traceless0929** [comment]
如果不是一台机器或不在一个内网的话 你需要自行想办法让SDK所在机器和OPQ本体所在机器实现互通才能使用
